services:
  go-app:
    container_name: go-app
    image: go-api-tutorial
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5542:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}